# Generated by Django 3.1.4 on 2021-01-18 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imageupload.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('fileid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('security', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='public', max_length=100)),
                ('file', models.FileField(upload_to=imageupload.models.user_directory)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
